---
title: "R Notebook"
output: github_document
---

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("dada2", version = "3.23")

```



```{r}

library(dada2); packageVersion("dada2")
```

```{r}
path <- "/home/rstudio/Dada2/Dada2/MiSeq_SOP" # CHANGE ME to the directory containing the fastq 
list.files(path)
```

```{r}
# Forward and reverse fastq filenames have format: SAMPLENAME_R1_001.fastq and SAMPLENAME_R2_001.fastq

fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE)) 
#F=forward correspond à la lecture de gauche à droite 

fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE)) 
# R=reverse correspond à la lecture de droite à gauche

# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
```

```{r}
plotQualityProfile(fnFs[1:2]) 
#visualisation des profils de contrôle qualité des seq forward
```

```{r}
plotQualityProfile(fnRs[1:2])
#profils des seq reverse
```

```{r}
# Place filtered files in filtered/ subdirectory
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
```

```{r}
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=FALSE) # On Windows set multithread=FALSE (only needed for filterAndTrim)
head(out)
# ici on supprime les valeurs à partir de 240 pour le fnFs et 160 pour fnRs car ces valeurs ont un score de qualité trop faible. On conserve cependant assez données pour que les 2 seq puissent se superposer
```

```{r}
errF <- learnErrors(filtFs, multithread=TRUE)
```

```{r}
errR <- learnErrors(filtRs, multithread=TRUE)
```

```{r}
plotErrors(errF, nominalQ=TRUE)
# permet d'avoir un graphe avec le taux d'erreur estimé pour les changements de bases possibles
```

```{r}
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
```

```{r}
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
#on applique l'algorithme d'interférence des core échantillons à la seq de données qu'on a filtré et recoupé plus tot
```

```{r}
dadaFs[[1]]
#on a débruité (enlevé les valeurs aberantes etc) des seq et on obtient 128 variants de sequence à partir des 1979 sequences unique données.
```

```{r}
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
# Inspect the merger data.frame from the first sample
head(mergers[[1]])
# on fusionne les seq forward et reverse qu'on a débruité au niveau des sequences chevauchantes 
```

```{r}
seqtab <- makeSequenceTable(mergers)
dim(seqtab)
```

```{r}
table(nchar(getSequences(seqtab)))
#on construit une table d' amplicon sequence variant (ASV). la table est une matrice où les lignes correspondent aux échantillons et les colonnes correspondent aux variants de sequences. la table contient 293 ASV
```

```{r}
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
#on enlève les chimères. les seq chimériques sont idéentifiées si elles peuvent être reconstruites en combinant les segments gauches et droits de 2 sequences "parentales", ces seq ne peuvent pas exister dans la nature mais sont créées lors de la formation des ASV
```

```{r}
sum(seqtab.nochim)/sum(seqtab)
#ici on a 4% des seq qui sont des seq chimériques et qui sont enlevées 
```

```{r}
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)
# ici on vérifie toutes les seq qui ont passées toutes les étapes du cheminement 
```

